[package]
name = "jay_lib"
version = "0.0.1"
license = "MIT"
authors = ["Jay Hu <digua1968@outlook.com>"]
description = "A small toolkit."
repository = "https://github.com/rdigua/jay_lib"
categories = ["lib"]
readme = "README.md"
keywords = ["toolkit"]
edition = "2021"



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
